name: Postgres Service Example

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  container-job:
    runs-on: ubuntu-latest
    container:
      image: node:10.16-jessie

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: demo
          POSTGRES_PASSWORD: demo
          POSTGRES_DB: demo
        ports:
          - 5433:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        volumes:
          - ./init:/docker-entrypoint-initdb.d  # Монтируем init.sql и init-db.sh

    steps:
      - uses: actions/checkout@v1
      - run: npm ci
        working-directory: ./postgres
      - run: ./init/init-db.sh  # Запускаем скрипт инициализации
        env:
          POSTGRES_USER: demo
          POSTGRES_PASSWORD: demo
          POSTGRES_DB: demo
          DB_USER: demo
          DB_PASSWORD: demo
          DB_NAME: demo
      - run: pytest test_database.py  # Запуск тестов
        working-directory: ./postgres
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5433
          DB_USER: demo
          DB_PASSWORD: demo
          DB_NAME: demo

  vm-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: demo
          POSTGRES_PASSWORD: demo
          POSTGRES_DB: demo
        ports:
          - 5433/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        volumes:
          - ./init:/docker-entrypoint-initdb.d

    steps:
      - uses: actions/checkout@v1
      - run: npm ci
        working-directory: ./postgres
      - run: ./init/init-db.sh
        env:
          POSTGRES_USER: demo
          POSTGRES_PASSWORD: demo
          POSTGRES_DB: demo
          DB_USER: demo
          DB_PASSWORD: demo
          DB_NAME: demo
      - run: pytest test_database.py
        working-directory: ./postgres
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5433
          DB_USER: demo
          DB_PASSWORD: demo
          DB_NAME: demo
