name: Postgres Service Example

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  container-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          DB_USER: demo
          DB_PASSWORD: demo
          DB_NAME: demo
        ports:
          - 5433:5432
        options: >-
          --env DB_USER=demo
          --env DB_PASSWORD=demo
          --env DB_NAME=demo
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        volumes:
          - ./database_tasks/init:/docker-entrypoint-initdb.d

    steps:
      - uses: actions/checkout@v4

      - name: Просмотр содержимого
        run: ls -la

      - name: Ожидание готовности БД
        run: sleep 10

      - name: Установка Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Установка Poetry и зависимостей
        run: |
          pip install poetry
          poetry install

      - name: Запуск тестов (container-job)
        run: poetry run pytest tests/test_database.py
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5433
          DB_USER: demo
          DB_PASSWORD: demo
          DB_NAME: demo

  vm-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          DB_USER: demo
          DB_PASSWORD: demo
          DB_NAME: demo
        ports:
          - 5433:5432
        options: >-
          --env DB_USER=demo
          --env DB_PASSWORD=demo
          --env DB_NAME=demo
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        volumes:
          - ./database_tasks/init:/docker-entrypoint-initdb.d


    steps:
      - uses: actions/checkout@v4

      - name: Просмотр содержимого
        run: ls -la

      - name: Ожидание готовности БД
        run: sleep 10

      - name: Установка Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Установка Poetry и зависимостей
        run: |
          pip install poetry
          poetry install

      - name: Запуск тестов (vm-job)
        run: poetry run pytest tests/test_database.py
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5433
          DB_USER: demo
          DB_PASSWORD: demo
          DB_NAME: demo
